# Generated by Django 4.2 on 2026-02-23 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otak_aplikasi', '0010_alter_categorypengumuman_options_alter_ektra_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='author_image',
        ),
    ]
