"""
Django settings for web_smknj project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv

# Load .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-default-key-change-me')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = [h.strip() for h in os.getenv('ALLOWED_HOSTS', '127.0.0.1,localhost,192.168.1.19').split(',')]


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_cleanup.apps.CleanupConfig',
    'ckeditor',
    'ckeditor_uploader',
    'otak_aplikasi',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'web_smknj.urls'

# ==========================================
# PRODUCTION SECURITY SETTINGS
# ==========================================
if not DEBUG:
    # Security headers
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'SAMEORIGIN'
    
    # HTTPS settings (aktifkan jika menggunakan SSL)
    SECURE_SSL_REDIRECT = False  # Set True jika SSL aktif
    SESSION_COOKIE_SECURE = False  # Set True jika SSL aktif
    CSRF_COOKIE_SECURE = False  # Set True jika SSL aktif
    
    # HSTS (HTTP Strict Transport Security)
    SECURE_HSTS_SECONDS = 0  # Set 31536000 (1 year) jika SSL aktif
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False
    SECURE_HSTS_PRELOAD = False
    
    # CSRF Trusted Origins untuk domain production
    CSRF_TRUSTED_ORIGINS = [
        'https://webtest.smknj.sch.id',
        'https://www.webtest.smknj.sch.id',
    ]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'web_smknj.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('DB_NAME', 'web_smknj_db'),
        'USER': os.getenv('DB_USER', 'root'),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '3306'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'id-id'
TIME_ZONE = 'Asia/Jakarta'  # PASTIKAN INI BENAR
USE_I18N = True
USE_L10N = True
USE_TZ = True  # PASTIKAN INI TRUE


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
STATIC_URL = os.getenv('STATIC_URL', '/static/')
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / 'staticfiles'  # untuk collectstatic

# Media files (User uploaded files)
MEDIA_URL = os.getenv('MEDIA_URL', '/media/')
MEDIA_ROOT = BASE_DIR / 'media'

# ==========================================
# PRODUCTION MEDIA/STATIC SETTINGS (cPanel)
# ==========================================
# Untuk production di cPanel, sesuaikan URL dengan domain
# Uncomment baris di bawah jika sudah production
# if not DEBUG:
#     STATIC_URL = 'https://webtest.smknj.sch.id/static/'
#     MEDIA_URL = 'https://webtest.smknj.sch.id/media/'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Cache configuration
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}

# Additional cache for sessions if needed
SESSION_ENGINE = 'django.contrib.sessions.backends.cached_db'

# Leader titles configuration
LEADER_TITLES = [
    'Kepala Sekolah',
    'Waka bidang Sarana dan Prasarana',
    'Waka bidang Kurikulum',
    'Waka bidang Hubungan Masyarakat',
    'Waka bidang Kesiswaan'
]

# CKEditor Configuration
CKEDITOR_UPLOAD_PATH = 'uploads/'
CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'full',
        'height': 300,
        'width': '100%',
    },
}

# Jazzmin Configuration - Minimal settings
JAZZMIN_SETTINGS = {
    "site_header": "Admin",
    "site_brand": "Admin Panel",
    "site_logo": "images/logo/logo.png",
    "welcome_sign": "Welcome",
    "copyright": "",
    "search_model": None,
    "user_avatar": None,
    "topmenu_links": [
        {"name": "Home", "url": "admin:index"},
    ],
    "show_ui_builder": False,
}


# Email Configuration
# Default to console backend for development
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Untuk production/sending real emails via Gmail:
#EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
#EMAIL_HOST = 'smtp.gmail.com'
#EMAIL_PORT = 587
#EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'alamatkeemailpengirim@gmail.com'  # Ganti dengan email pengirim
#EMAIL_HOST_USER = [EMAIL_ADDRESS]' # Ganti dengan email asli anda untuk mengirim
# EMAIL_HOST_PASSWORD = 'password_app_anda'  # App Password, bukan password email biasa
#EMAIL_HOST_PASSWORD = 'password_app_anda' # Ganti dengan App Password anda
# RECIPIENT_ADDRESS = 'smknurja.paiton@gmail.com'
#RECIPIENT_ADDRESS = 'smknurja.paiton@gmail.com'


